emotion_detection_task:
  description: >
    Analyze the user's input: "{user_input}"
    Identify their primary emotion (e.g., sadness, anxiety, neutral) and provide a short emotional summary.
  expected_output: >
    A short emotion label, e.g., "User feels anxious."
  output_key: emotion_summary
  agent: emotion_detector

safety_check_task:
  description: >
    Review: "{user_input}"
    Check for crisis-related language (e.g., suicidal thoughts, self-harm). Respond if critical or confirm safety.
  expected_output: >
    "Crisis detected: ..." or "No red flags detected."
  output_key: safety_result
  agent: safety_agent
  context:
    - emotion_detection_task

rag_retrieval_task:
  description: >
    Based on the user's emotional state, retrieve concise mental health tips from the corpus.
  expected_output: >
    1–2 short tips, e.g., "Take a walk in nature. Try deep breathing exercises."
  output_key: retrieved_tips
  agent: rag_retriever
  context:
    - emotion_detection_task

rag_reading_task:
  description: >
    Summarize the tips retrieved in a helpful and brief tone.
  expected_output: >
    A 1-2 line practical summary of the tips.
  output_key: summarized_tips
  agent: rag_reader
  context:
    - emotion_detection_task
    - rag_retrieval_task

suggestion_task:
  description: >
    Give 1-2 practical, empathetic suggestions based on emotional state and retrieved tips.
  expected_output: >
    Very short suggestions (1-2 lines). E.g., "Try a short breathing exercise. Take a break from screens."
  output_key: suggestions
  agent: suggestion_agent
  context:
    - emotion_detection_task
    - safety_check_task
    - rag_retrieval_task
    - rag_reading_task

orchestrate_task:
  description: >
    Respond to: "{user_input}" with an adaptive tone and length.
    - For greetings or neutral input: be short and friendly.
    - For moderate emotions (e.g., anxiety, stress): respond with 2-3 concise lines.
    - For crisis-level input: give a longer, supportive message with clear help suggestions.
  expected_output: >
    A concise, human-like response adapted to the emotional tone and urgency.
  output_key: final_response
  agent: orchestrator
  context:
    - emotion_detection_task
    - safety_check_task
    - rag_retrieval_task
    - rag_reading_task
    - suggestion_task